#!/bin/bash

# This script implements a gerrit hook to refresh our local gerrit repository with the
# origin one from github.


set -e # exit on any error return val


# --project <project name> --refname <refname> --uploader <uploader> --oldrev <sha1> --newrev <sha1>

while [[ $# > 1 ]] ; do
  case "$1" in
    --change)
        change=$2 ; shift ;;
    --change-url)
        change_url=$2 ; shift ;;
    --change-owner)
        change_owner=$2 ; shift ;;
    --project)
        project=$2 ; shift ;;
    --branch)
        branch=$2 ; shift ;;
    --submitter)
        submitter=$2 ; shift ;;
    --commit)
        commit=$2 ; shift ;;
    --refname)
        refname=$2 ; shift ;;
    --uploader)
        uploader=$2 ; shift ;;
    --oldrev)
        oldrev=$2 ; shift ;;
    --newrev)
        newrev=$2 ; shift ;;
  esac
  shift
done


branch=$(echo "$refname" | sed "s-refs/for/--")

echo "Ensuring gerrit in sync with github on branch $branch."
git fetch origin $branch
git update-ref refs/heads/$branch FETCH_HEAD

